### ISSUE TITLE
Release tarballs only include references to Git LFS

### ISSUE THREAD

**Issue by roelj** [UMCUGenetics/Dx_tracks#1]
Would it be possible to make complete/fat release tarballs , rather than a bunch of references to the actual data stored in the LFS?

**Comment by rernst** [comment]
This is possible, although this would need to be done manually. Which is of course error prone. Can't you use git-lfs to download the files?

**Comment by roelj** [comment]
Right.  Well, probably I can, but to automate that when distributing it along with programs that need it is quite some work.

For example, we could distribute the data along with packages in Guix by adding a `dx-tracks` package recipe:
```
(define-public dx-tracks
  (package
    (name "dx-tracks")
    (version "1.2.1")
    (source (origin
                   (method url-fetch)
                   (uri "https://github.com/UMCUGenetics/Dx_tracks/archive/v1.2.1.tar.gz")
                   (sha256
                     (base32 "..."))))
    ...))
```

To do that by using `git-lfs` we would need to:
* Add `git-lfs` to Guix;
* Modify the git-downloader in Guix to use `git-lfs` (and upstream these changes).

The second item is the most work.

**Comment by rernst** [comment]
Sorry for my late reply, forgot about this issue.

I understand that it will take time to support git-lfs. However, I think this is nevertheless the best way to tackle this problem. I don't like the fact that the first solution is a manual step that has to be done everytime with a new release. In the end it will take more time and as I said before is error prone. We have seen this before with binaries not matching the actual release/tag on git/github.

For now I will add a .tar.gz to the last release, but I would be better if we get git-lfs support in the future.

**Comment by roelj** [comment]
I understand the hassle.  Nevertheless, the release tarballs (generated by Github) simply don't work.  A user cannot assume to have the data/code needed to produce the end-result this repository tries to provide (the datasets), by downloading the release tarballs.

**Comment by rernst** [comment]
Do you have experience with a continuous integration service (travis?) who could do this for us? Thus: on release, automatically create a zip and attach to the github relase?

**Comment by roelj** [comment]
Yes, but maybe a git hook after creating a tag is all you need.  With it, you can generate a tarball/zip archive upon creating a tag.  Granted, you'd still have to upload it to Github manually. (If there was an (S)FTP location to upload them to, you could let the git hook do that).

A continuous integration service is more suited for automatic testing on how a new release fits into the bigger picture.
